// <auto-generated />
using System;
using BlackoutRugbyDashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlackoutRugbyDashboard.Migrations
{
    [DbContext(typeof(DashboardDbContext))]
    partial class DashboardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("BlackoutRugbyDashboard.Data.DashboardUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EncryptedMemberKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LinkedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BlackoutRugbyDashboard.Data.FixtureRow", b =>
                {
                    b.Property<int>("FixtureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BotMatch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Competition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryIso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DataRemoved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GuestTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MatchFinishUnix")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MatchStartUnix")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WeatherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FixtureId");

                    b.ToTable("Fixtures");
                });

            modelBuilder.Entity("BlackoutRugbyDashboard.Data.MatchSummaryRow", b =>
                {
                    b.Property<int>("FixtureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Corporate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Covered")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GuestIntensity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuestPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeIntensity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomePoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InjuriesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Members")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Standing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubstitutionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Uncovered")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WeatherId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("WeatherNight")
                        .HasColumnType("INTEGER");

                    b.HasKey("FixtureId");

                    b.ToTable("MatchSummaries");
                });

            modelBuilder.Entity("BlackoutRugbyDashboard.Data.MatchSummaryScorerRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FixtureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScorerType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MatchSummaryScorers");
                });

            modelBuilder.Entity("BlackoutRugbyDashboard.Data.PlayerFixtureRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BadKicks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bad_kicks");

                    b.Property<int>("BadUpAndUnders")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bad_up_and_unders");

                    b.Property<int>("BallTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ball_time");

                    b.Property<int>("BeatenDefenders")
                        .HasColumnType("INTEGER")
                        .HasColumnName("beaten_defenders");

                    b.Property<int>("Conversions")
                        .HasColumnType("INTEGER")
                        .HasColumnName("conversions");

                    b.Property<int>("CupCaps")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cup_caps");

                    b.Property<int>("DropGoals")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dropgoals");

                    b.Property<int>("EnergyAfter")
                        .HasColumnType("INTEGER")
                        .HasColumnName("energy_after");

                    b.Property<int>("EnergyBefore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("energy_before");

                    b.Property<int>("Fights")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fights");

                    b.Property<int>("FixtureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ForwardPasses")
                        .HasColumnType("INTEGER")
                        .HasColumnName("forward_passes");

                    b.Property<int>("FriendlyCaps")
                        .HasColumnType("INTEGER")
                        .HasColumnName("friendly_caps");

                    b.Property<int>("GoodKicks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("good_kicks");

                    b.Property<int>("GoodUpAndUnders")
                        .HasColumnType("INTEGER")
                        .HasColumnName("good_up_and_unders");

                    b.Property<int>("HandlingErrors")
                        .HasColumnType("INTEGER")
                        .HasColumnName("handling_errors");

                    b.Property<int>("Injuries")
                        .HasColumnType("INTEGER")
                        .HasColumnName("injuries");

                    b.Property<int>("Intercepts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("intercepts");

                    b.Property<int>("Jersey")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KickingMetres")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kicking_metres");

                    b.Property<int>("Kicks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kicks");

                    b.Property<int>("KicksOutOnTheFull")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kicks_out_on_the_full");

                    b.Property<int>("Knockons")
                        .HasColumnType("INTEGER")
                        .HasColumnName("knockons");

                    b.Property<int>("LeagueCaps")
                        .HasColumnType("INTEGER")
                        .HasColumnName("league_caps");

                    b.Property<int>("Linebreaks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("linebreaks");

                    b.Property<int>("LineoutsConceded")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lineouts_conceded");

                    b.Property<int>("LineoutsSecured")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lineouts_secured");

                    b.Property<int>("LineoutsStolen")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lineouts_stolen");

                    b.Property<int>("MetresGained")
                        .HasColumnType("INTEGER")
                        .HasColumnName("metres_gained");

                    b.Property<int>("MinutesPlayed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("minutes_played");

                    b.Property<int>("MissedConversions")
                        .HasColumnType("INTEGER")
                        .HasColumnName("missed_conversions");

                    b.Property<int>("MissedDropGoals")
                        .HasColumnType("INTEGER")
                        .HasColumnName("missed_dropgoals");

                    b.Property<int>("MissedPenalties")
                        .HasColumnType("INTEGER")
                        .HasColumnName("missed_penalties");

                    b.Property<int>("MissedTackles")
                        .HasColumnType("INTEGER")
                        .HasColumnName("missed_tackles");

                    b.Property<int>("NationalCaps")
                        .HasColumnType("INTEGER")
                        .HasColumnName("national_caps");

                    b.Property<int>("OtherCaps")
                        .HasColumnType("INTEGER")
                        .HasColumnName("other_caps");

                    b.Property<int>("Penalties")
                        .HasColumnType("INTEGER")
                        .HasColumnName("penalties");

                    b.Property<int>("PenaltiesConceded")
                        .HasColumnType("INTEGER")
                        .HasColumnName("penalties_conceded");

                    b.Property<int>("Played")
                        .HasColumnType("INTEGER")
                        .HasColumnName("played");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RedCards")
                        .HasColumnType("INTEGER")
                        .HasColumnName("red_cards");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuccessfulLineoutThrows")
                        .HasColumnType("INTEGER")
                        .HasColumnName("successful_lineout_throws");

                    b.Property<int>("Tackles")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tackles");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_points");

                    b.Property<int>("Tries")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tries");

                    b.Property<int>("TryAssists")
                        .HasColumnType("INTEGER")
                        .HasColumnName("try_assists");

                    b.Property<int>("Turnovers")
                        .HasColumnType("INTEGER")
                        .HasColumnName("turnovers");

                    b.Property<int>("UnderTwentyCaps")
                        .HasColumnType("INTEGER")
                        .HasColumnName("under_twenty_caps");

                    b.Property<int>("UnderTwentyWorldCupCaps")
                        .HasColumnType("INTEGER")
                        .HasColumnName("under_twenty_world_cup_caps");

                    b.Property<int>("UnsuccessfulLineoutThrows")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unsuccessful_lineout_throws");

                    b.Property<int>("UpAndUnders")
                        .HasColumnType("INTEGER")
                        .HasColumnName("up_and_unders");

                    b.Property<int>("WorldCupCaps")
                        .HasColumnType("INTEGER")
                        .HasColumnName("world_cup_caps");

                    b.Property<int>("YellowCards")
                        .HasColumnType("INTEGER")
                        .HasColumnName("yellow_cards");

                    b.HasKey("Id");

                    b.ToTable("PlayerFixtures");
                });

            modelBuilder.Entity("BlackoutRugbyDashboard.Data.PlayerSeasonRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvKickingMetres")
                        .HasColumnType("INTEGER")
                        .HasColumnName("avkickingmetres");

                    b.Property<int>("BadKicks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("badkicks");

                    b.Property<int>("BadUpAndUnders")
                        .HasColumnType("INTEGER")
                        .HasColumnName("badupandunders");

                    b.Property<int>("BallTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("balltime");

                    b.Property<int>("BeatenDefenders")
                        .HasColumnType("INTEGER")
                        .HasColumnName("beatendefenders");

                    b.Property<int>("Conversions")
                        .HasColumnType("INTEGER")
                        .HasColumnName("conversions");

                    b.Property<int>("CupCaps")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cupcaps");

                    b.Property<int>("DropGoals")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dropgoals");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Fights")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fights");

                    b.Property<int>("ForwardPasses")
                        .HasColumnType("INTEGER")
                        .HasColumnName("forwardpasses");

                    b.Property<int>("FriendlyCaps")
                        .HasColumnType("INTEGER")
                        .HasColumnName("friendlycaps");

                    b.Property<int>("GoodKicks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("goodkicks");

                    b.Property<int>("GoodUpAndUnders")
                        .HasColumnType("INTEGER")
                        .HasColumnName("goodupandunders");

                    b.Property<int>("HandlingErrors")
                        .HasColumnType("INTEGER")
                        .HasColumnName("handlingerrors");

                    b.Property<int>("Injuries")
                        .HasColumnType("INTEGER")
                        .HasColumnName("injuries");

                    b.Property<int>("Intercepts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("intercepts");

                    b.Property<int>("KickingMetres")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kickingmetres");

                    b.Property<int>("Kicks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kicks");

                    b.Property<int>("KicksOutOnTheFull")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kicksoutonthefull");

                    b.Property<int>("Knockons")
                        .HasColumnType("INTEGER")
                        .HasColumnName("knockons");

                    b.Property<int>("LeagueCaps")
                        .HasColumnType("INTEGER")
                        .HasColumnName("leaguecaps");

                    b.Property<int>("Linebreaks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("linebreaks");

                    b.Property<int>("LineoutsConceded")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lineoutsconceded");

                    b.Property<int>("LineoutsSecured")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lineoutssecured");

                    b.Property<int>("LineoutsStolen")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lineoutsstolen");

                    b.Property<int>("MetresGained")
                        .HasColumnType("INTEGER")
                        .HasColumnName("metresgained");

                    b.Property<int>("MissedConversions")
                        .HasColumnType("INTEGER")
                        .HasColumnName("missedconversions");

                    b.Property<int>("MissedDropGoals")
                        .HasColumnType("INTEGER")
                        .HasColumnName("misseddropgoals");

                    b.Property<int>("MissedPenalties")
                        .HasColumnType("INTEGER")
                        .HasColumnName("missedpenalties");

                    b.Property<int>("MissedTackles")
                        .HasColumnType("INTEGER")
                        .HasColumnName("missedtackles");

                    b.Property<int>("NationalCaps")
                        .HasColumnType("INTEGER")
                        .HasColumnName("nationalcaps");

                    b.Property<int>("OtherCaps")
                        .HasColumnType("INTEGER")
                        .HasColumnName("othercaps");

                    b.Property<int>("Penalties")
                        .HasColumnType("INTEGER")
                        .HasColumnName("penalties");

                    b.Property<int>("PenaltiesConceded")
                        .HasColumnType("INTEGER")
                        .HasColumnName("penaltiesconceded");

                    b.Property<int>("PenaltyTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("penaltytime");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RedCards")
                        .HasColumnType("INTEGER")
                        .HasColumnName("redcards");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuccessfulLineoutThrows")
                        .HasColumnType("INTEGER")
                        .HasColumnName("successfullineoutthrows");

                    b.Property<int>("Tackles")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tackles");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("INTEGER")
                        .HasColumnName("totalpoints");

                    b.Property<int>("Tries")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tries");

                    b.Property<int>("TryAssists")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tryassists");

                    b.Property<int>("TurnoversWon")
                        .HasColumnType("INTEGER")
                        .HasColumnName("turnoverswon");

                    b.Property<int>("UnderTwentyCaps")
                        .HasColumnType("INTEGER")
                        .HasColumnName("undertwentycaps");

                    b.Property<int>("UnderTwentyWorldCupCaps")
                        .HasColumnType("INTEGER")
                        .HasColumnName("undertwentyworldcupcaps");

                    b.Property<int>("UnsuccessfulLineoutThrows")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unsuccessfullineoutthrows");

                    b.Property<int>("UpAndUnders")
                        .HasColumnType("INTEGER")
                        .HasColumnName("upandunders");

                    b.Property<int>("WorldCupCaps")
                        .HasColumnType("INTEGER")
                        .HasColumnName("worldcupcaps");

                    b.Property<int>("YellowCards")
                        .HasColumnType("INTEGER")
                        .HasColumnName("yellowcards");

                    b.HasKey("Id");

                    b.ToTable("PlayerSeasons");
                });

            modelBuilder.Entity("BlackoutRugbyDashboard.Data.TeamFactRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AverageTop15Csr")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Bot")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryIso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NationalRank")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("RankingPoints")
                        .HasColumnType("REAL");

                    b.Property<int>("RegionalRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorldRank")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TeamFacts");
                });

            modelBuilder.Entity("BlackoutRugbyDashboard.Data.TeamFixtureStatRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BadKicks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bad_kicks");

                    b.Property<int>("BadUpAndUnders")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bad_up_and_unders");

                    b.Property<int>("BallTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ball_time");

                    b.Property<int>("Category1Injuries")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_1_injuries");

                    b.Property<int>("Category2Injuries")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_2_injuries");

                    b.Property<int>("Category3Injuries")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_3_injuries");

                    b.Property<int>("Category4Injuries")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_4_injuries");

                    b.Property<int>("Category5Injuries")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_5_injuries");

                    b.Property<int>("Category6Injuries")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_6_injuries");

                    b.Property<int>("Conversions")
                        .HasColumnType("INTEGER")
                        .HasColumnName("conversions");

                    b.Property<int>("DropGoals")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dropgoals");

                    b.Property<int>("Fights")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fights");

                    b.Property<int>("FixtureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ForwardPasses")
                        .HasColumnType("INTEGER")
                        .HasColumnName("forward_passes");

                    b.Property<int>("GoodKicks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("good_kicks");

                    b.Property<int>("GoodUpAndUnders")
                        .HasColumnType("INTEGER")
                        .HasColumnName("good_up_and_unders");

                    b.Property<string>("Half")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HandlingErrors")
                        .HasColumnType("INTEGER")
                        .HasColumnName("handling_errors");

                    b.Property<int>("Injuries")
                        .HasColumnType("INTEGER")
                        .HasColumnName("injuries");

                    b.Property<int>("InjuryBreaks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("injury_breaks");

                    b.Property<int>("Intercepts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("intercepts");

                    b.Property<int>("KickingMetres")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kicking_metres");

                    b.Property<int>("Kicks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kicks");

                    b.Property<int>("KicksOutOnTheFull")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kicks_out_on_the_full");

                    b.Property<int>("Knockons")
                        .HasColumnType("INTEGER")
                        .HasColumnName("knockons");

                    b.Property<int>("Linebreaks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("linebreaks");

                    b.Property<int>("LineoutsAgainstThrow")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lineouts_against_throw");

                    b.Property<int>("LineoutsLost")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lineouts_lost");

                    b.Property<int>("LineoutsSecured")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lineouts_secured");

                    b.Property<int>("LineoutsThrown")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lineouts_thrown");

                    b.Property<int>("LineoutsWon")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lineouts_won");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("matches_played");

                    b.Property<int>("MaulsWon")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mauls_won");

                    b.Property<int>("MetresGained")
                        .HasColumnType("INTEGER")
                        .HasColumnName("metres_gained");

                    b.Property<int>("MinutesIn22")
                        .HasColumnType("INTEGER")
                        .HasColumnName("minutes_in_22");

                    b.Property<int>("MissedConversions")
                        .HasColumnType("INTEGER")
                        .HasColumnName("missed_conversions");

                    b.Property<int>("MissedDropGoals")
                        .HasColumnType("INTEGER")
                        .HasColumnName("missed_dropgoals");

                    b.Property<int>("MissedPenalties")
                        .HasColumnType("INTEGER")
                        .HasColumnName("missed_penalties");

                    b.Property<int>("MissedTackles")
                        .HasColumnType("INTEGER")
                        .HasColumnName("missed_tackles");

                    b.Property<int>("Penalties")
                        .HasColumnType("INTEGER")
                        .HasColumnName("penalties");

                    b.Property<int>("PenaltiesConceded")
                        .HasColumnType("INTEGER")
                        .HasColumnName("penalties_conceded");

                    b.Property<int>("PenaltiesWon")
                        .HasColumnType("INTEGER")
                        .HasColumnName("penalties_won");

                    b.Property<int>("Phases")
                        .HasColumnType("INTEGER")
                        .HasColumnName("phases");

                    b.Property<int>("Possession")
                        .HasColumnType("INTEGER")
                        .HasColumnName("possession");

                    b.Property<int>("RedCards")
                        .HasColumnType("INTEGER")
                        .HasColumnName("red_cards");

                    b.Property<int>("RucksWon")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rucks_won");

                    b.Property<int>("ScrumsAgainstPutIn")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scrums_against_put_in");

                    b.Property<int>("ScrumsLost")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scrums_lost");

                    b.Property<int>("ScrumsPutIn")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scrums_put_in");

                    b.Property<int>("ScrumsSecured")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scrums_secured");

                    b.Property<int>("ScrumsWon")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scrums_won");

                    b.Property<int>("SevenplusPhases")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sevenplus_phases");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tackles")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tackles");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Territory")
                        .HasColumnType("INTEGER")
                        .HasColumnName("territory");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_points");

                    b.Property<int>("Tries")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tries");

                    b.Property<int>("Turnovers")
                        .HasColumnType("INTEGER")
                        .HasColumnName("turnovers");

                    b.Property<int>("TurnoversConceded")
                        .HasColumnType("INTEGER")
                        .HasColumnName("turnovers_conceded");

                    b.Property<int>("UpAndUnders")
                        .HasColumnType("INTEGER")
                        .HasColumnName("up_and_unders");

                    b.Property<int>("YellowCards")
                        .HasColumnType("INTEGER")
                        .HasColumnName("yellow_cards");

                    b.HasKey("Id");

                    b.ToTable("TeamFixtureStats");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BlackoutRugbyDashboard.Data.DashboardUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BlackoutRugbyDashboard.Data.DashboardUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlackoutRugbyDashboard.Data.DashboardUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BlackoutRugbyDashboard.Data.DashboardUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
